on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

name: Conftest YAML files
jobs:
  conftest-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalronin/github-actions/conftest-yaml@master
        env:
          POLICY_DIR: "rego_policies"
          CONFTEST_OPTIONS: "--no-color"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
